module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'Tours',
      [
        {
          name: 'Путешествие на море',
          price: 500,
          description: 'Замечательное путешествие на море',
          authorId: 1,
          catTId: 1,
          location: 'Морской курорт',
          date: '2024-07-15',
          endDate: '2024-07-30',
          places: 10,
          pathImg: 'https://s0.rbk.ru/v6_top_pics/media/img/1/02/346831925047021.webp',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Горные вершины',
          price: 700,
          description: 'Увлекательное восхождение на горные вершины',
          authorId: 2,
          catTId: 2,
          location: 'Горы',
          date: '2024-08-10',
          endDate: '2024-08-20',
          places: 8,
          pathImg: 'https://gorodprima.ru/wp-content/uploads/2022/06/3-2.png',

          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Экскурсия по достопримечательностям',
          price: 300,
          description: 'Увлекательное знакомство с историей и культурой',
          authorId: 3,
          catTId: 3,
          location: 'Различные города',
          date: '2024-09-05',
          endDate: '2024-09-15',
          places: 15,
          pathImg:
            'https://34travel.me/media/upload/images/2018/june/pohod/tommy-lisbin-211935-unsplash.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Поход по лесу',
          price: 200,
          description: 'Исследуйте дремучие леса и насладитесь природой',
          authorId: 1,
          catTId: 4,
          location: 'Лесной массив',
          date: '2024-10-05',
          endDate: '2024-10-12',
          places: 12,
          pathImg:
            'https://pesh-lesh.com/wp-content/uploads/2020/04/%D0%A7%D1%82%D0%BE-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%B2-%D0%BF%D0%BE%D1%85%D0%BE%D0%B4.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Велотур по городу',
          price: 150,
          description: 'Ознакомьтесь с городскими достопримечательностями на велосипеде',
          authorId: 3,
          catTId: 5,
          location: 'Городские улицы',
          date: '2024-05-20',
          endDate: '2024-05-22',
          places: 10,
          pathImg: 'https://www.russiadiscovery.ru/storage/images/tours/2963/205/original.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'ЭЛЬБРУС ААААОАООАОАОАА',
          price: 150,
          description: 'НВОАЯ ЖИЗНЬ ЗА ТРИ 3 МЕСЯЦА',
          authorId: 2,
          catTId: 5,
          location: 'ГОГАРЕНСКИЙ',
          date: '2024-05-20',
          endDate: '2024-05-22',
          places: 10,
          pathImg:
            'https://titam.ru/wp-content/uploads/2023/01/%D0%92%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D1%8B-%D0%AD%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D0%B0-%D0%BE%D1%82-%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%B8-%D0%93%D0%B0%D1%80%D0%B0%D0%B1%D0%B0%D1%88%D0%B8.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Tours', null, {});
  },
};
